spring:
  datasource:
    url: jdbc:h2:mem:fundraiser
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
# Uncomment the lines below for development/debugging purposes:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  h2:
#    console:
#      enabled: true

currency:
  unirate:
    base-url: https://api.unirateapi.com/api/convert
    api-key: ${UNIRATE_API_KEY:provide_your_api_key}
